name: CI

on:
  push:

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:16-bullseye

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Maps the service container port to the host
          - 6379:6379
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cathe-node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: cathe-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

