name: CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Maps the service container port to the host
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cathe-node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: cathe-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: error-commands
        run: |
          echo ::error::This is and error
          echo ::warning::This is a warning
          echo ::set-output name=error::This is an error
          echo ::debug::This is a debug message
          echo ::mask::This is a secret

