name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cathe-node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: cathe-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

